### ISSUE TITLE
Wrong order hosts file gen

### ISSUE THREAD

**Issue by FadeMind** [funilrys/dead-hosts#3]
@funilrys  hi, I saw that generated hosts files have wrong order:
```
domain.com 0.0.0.0
```

Should be:

```
0.0.0.0 domain.com
```

**Comment by funilrys** [comment]
Thanks for reporting! 
P.S: As all https://github.com/dead-hosts are under [PyFunceble](https://github.com/funilrys/PyFunceble) I also reported it here (https://github.com/funilrys/PyFunceble/issues/1)

**Comment by funilrys** [comment]
Closing because https://github.com/funilrys/PyFunceble/issues/1 has been fixed by https://github.com/funilrys/PyFunceble/commit/2fd816097d54c17a68edbbbbc9736c3d1d37261e.

Thanks again @FadeMind :+1: :tada:
